### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by DogsLike** [xiaohouzi510/python_kcp#1]
专家您好，我在工程中导入py_kcp.py出现报错
![111](https://user-images.githubusercontent.com/5936439/41529253-0e622d04-731f-11e8-9b87-6e9768e30efb.png)
![222](https://user-images.githubusercontent.com/5936439/41529257-11f1042c-731f-11e8-9622-8a401fa34a8b.png)

python版本2.7

**Comment by DogsLike** [comment]
均提示 引用 不存在

**Comment by XuJianxing** [comment]
> 均提示 引用 不存在

你好，请问这个问题解决了吗
